# Server configuration
server.port=8080

# Database configuration
spring.datasource.url=jdbc:sqlite:knowledgedb.db
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.jpa.database-platform=org.sqlite.hibernate.dialect.SQLiteDialect

# Hibernate configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Vaadin configuration
vaadin.launch-browser=true
vaadin.productionMode=false

# Logging
logging.level.com.kdb.standalone=DEBUG
